name: publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to node machine
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd login.kinzig.schule
            pm2 stop src/index.js
            git pull
            npm install
            npx tsc
            pm2 start --name login.kinzig.schule-gh src/index.js -- production