name: publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to node machine
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls -larth
            echo "Test?"